install:
  - cmd: git submodule update --init --recursive
  - ps: nuget restore OpenConsole.sln
  
build:
  parallel: true                  # enable MSBuild parallel builds
  project: OpenConsole.sln      # path to Visual Studio solution or project

platform: x64
configuration: Release
