install:
  - ps: nuget restore OpenConsole.sln
  
build:
  parallel: true                  # enable MSBuild parallel builds
  project: OpenConsole.sln      # path to Visual Studio solution or project
  
